name: QA Build

on:
  pull_request:
    types: [ labeled ]
  pull_request_review:
      types: [submitted]

jobs:
  build:
    if: github.event.label.name == 'qa_ready' || github.event.review.state == 'APPROVED'
    name: "Build Zip For QA"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP 7.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          extensions: mbstring, intl, zip
          tools: composer

      - name: Verify PHP version
        run: php -v

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Install npm dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Generate plugin zip
        run: |
          # Create a clean directory structure
          mkdir -p temp-build
          
          # Copy all files except excluded ones directly to temp-build
          rsync -av \
            --exclude='temp-build' \
            --exclude='temp-plugin' \
            --exclude='node_modules' \
            --exclude='src' \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='.gitignore' \
            --exclude='.editorconfig' \
            --exclude='composer.lock' \
            --exclude='package-lock.json' \
            --exclude='*.zip' \
            --exclude='README.md' \
            --exclude='phpcs.xml' \
            --exclude='webpack.config.js' \
            --exclude='package.json' \
            ./ temp-build/
          
          # Create the zip from temp-build contents
          cd temp-build
          zip -r ../lifecoachhub.zip .
          cd ..
          
          # Clean up
          rm -rf temp-build
          
          # Verify zip contents
          echo "Zip contents:"
          unzip -l lifecoachhub.zip | head -20

      - name: Upload Zip
        uses: actions/upload-artifact@v4
        with:
          name: lifecoachhub
          path: lifecoachhub.zip
